from typing import List, Optional

class CommentHandler:
    def __init__(self, client: "FacebookClient") -> None: ...
    def get_instagram_comments(self, media_id: str) -> List["Comment"]: ...
    def _parse_comment_item(self, comment: dict) -> "Comment": ...
    def get_post_mentions(
        self, insta_id: str, media_id: str
    ) -> Optional["PostMention"]: ...
    def get_comment_mentions(
        self, insta_id: str, comment_id: str
    ) -> Optional["CommentMention"]: ...
    def reply_to_mention(
        self, insta_id: str, comment_id: Optional[str], message: str, media_id: str
    ) -> Optional["ReplyMention"]: ...
