from typing import List, Optional, Dict

class HashtagHandler:
    def __init__(self, client: "FacebookClient") -> None: ...
    def search_hashtag(self, insta_id: str, query: str) -> Optional[str]: ...
    def get_hashtag_info(self, hashtag_id: str) -> Dict: ...
    def get_recent_media(self, hashtag_id: str, insta_id: str) -> Dict: ...
    def get_top_media(self, hashtag_id: str, insta_id: str) -> List[Dict]: ...
