from typing import List

class MediaHandler:
    def __init__(self, client: "FacebookClient") -> None: ...
    def get_instagram_media(self, insta_id: str) -> List["Media"]: ...
    def _parse_media_item(self, media: dict) -> "Media": ...
    def get_instagram_insights(self, insta_id: str) -> List["Insight"]: ...
