from typing import List

class StoryHandler:
    def __init__(self, client: "FacebookClient") -> None: ...
    def get_instagram_stories(self, insta_id: str) -> List["Story"]: ...
    def _parse_story_item(self, story: dict) -> "Story": ...
