# Stub for sage_meta.service.handlers.account

from typing import List, Optional

class AccountHandler:
    def __init__(self, client: "FacebookClient") -> None: ...
    def get_accounts(self) -> List["FacebookPageData"]: ...
    def _parse_page_data(self, account: dict) -> "FacebookPageData": ...
    def get_instagram_business_account(self, page: "FacebookPageData") -> Optional["InstagramAccount"]: ...
    def get_account_settings(self) -> dict: ...
    def _make_request(self, url: str, params: dict) -> "requests.Response": ...
