
from typing import Optional, Dict

class CopyrightManager:
    def __init__(self, access_token: str) -> None: ...
    def check_copyright_status_unpublished(self, container_id: str) -> dict: ...
    def check_copyright_status_published(self, media_id: str) -> dict: ...
